name: Archive Project

on:
  push:
    branches:
      - main

jobs:
  zip-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Install ZIP
        run: sudo apt-get install zip

      - name: Create Archive Directory
        run: mkdir -p archive

      - name: Zip project
        run: zip -r archive/${{ github.sha }}.zip . -x "*.git*" ".github/*" "archive/*"
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.PAT }}
          commit_message: update archive
